

# 4.2.0_1

> android4.4.2

### LOG_CONTENT:

```java
java.lang.RuntimeException: An error occured while executing doTask()
at com.openet.hotel.task.BaseTask$2.void done()(SourceFile:73)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at com.openet.hotel.task.BaseTask.void run()(SourceFile:151)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
at com.openet.hotel.webhacker.database.OrderDBHelper.java.util.ArrayList getTop10ValideOrder()(SourceFile:196)
at com.openet.hotel.order.OrderListFragment$3.void onTaskLoading$3c15c4a3(com.openet.hotel.protocol.model.OrderListResult)(SourceFile:1185)
                                              void onTaskLoading$2f51880f(java.lang.Object,java.lang.Exception)
at com.openet.hotel.task.InnmallTask.java.lang.Object doInBackground()(SourceFile:252)
at com.openet.hotel.task.BaseTask.java.lang.Object doTask()(SourceFile:87)
at com.openet.hotel.task.BaseTask$1.java.lang.Object call()(SourceFile:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 morejava.lang.NullPointerException: Attempt to invoke virtual method 'android.database.sqlite.SQLiteDatabase android.content.Context.openOrCreateDatabase(java.lang.String, int, android.database.sqlite.SQLiteDatabase$CursorFactory, android.database.DatabaseErrorHandler)' on a null object reference
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
at com.openet.hotel.webhacker.database.OrderDBHelper.java.util.ArrayList getTop10ValideOrder()(SourceFile:196)
at com.openet.hotel.order.OrderListFragment$3.void onTaskLoading$3c15c4a3(com.openet.hotel.protocol.model.OrderListResult)(SourceFile:1185)
                                              void onTaskLoading$2f51880f(java.lang.Object,java.lang.Exception)
at com.openet.hotel.task.InnmallTask.java.lang.Object doInBackground()(SourceFile:252)
at com.openet.hotel.task.BaseTask.java.lang.Object doTask()(SourceFile:87)
at com.openet.hotel.task.BaseTask$1.java.lang.Object call()(SourceFile:57)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at com.openet.hotel.task.BaseTask.void run()(SourceFile:151)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

### SOURCE_CODE:

```java
//xxxFragment:
localOrders = OrderDBHelper.getInstance(getActivity()).getTop10ValideOrder();
```

### WHY:

DatabaseHelper mOpenHelper.getInstance from activity is wrong. 

You are attempting to do something with the Activity instance before the super.onCreate() call in the onCreate() method of that Activity

### FIX_CODE:

```java
//xxxFragment:
localOrders = OrderDBHelper.getInstance(InnApplication.getInstace()).getTop10ValideOrder();
```

### StackOverflow Reference:

[android null pointer exception on getReadableDatabase](https://stackoverflow.com/questions/32289911/android-null-pointer-exception-on-getreadabledatabase)






